export {default as Hero} from './Hero'
export {default as Mailchimp} from './Mailchimp'
export {default as TextSection} from './TextSection'
export {default as ImageSection} from './ImageSection'
export {default as Contact} from './Contact'
export {default as contactForm} from './Contact'
export {default as Product} from './Product'
export {default as Gallery} from './Gallery'
// export {default as ProductsPage} from './Products'
